### ISSUE TITLE
Arsenal: Camera mouse movement is inverted

### ISSUE THREAD

**Issue by bux** [alganthe/ACE3ganthe#24]
Based on commit: f13d0ebc5ba17502a689c2b6af9444bd10f1d2f9

Might be intentional

* Open Arsenal
* Move the camera using mouse dragging
* Dragging the mouse to the left makes the camera move to the left and vice versa
* Dragging the mouse to the bottom makes the camera move to the bottom and vice versa

Then 

* Open vanilla Arsenal
* Move the camera using mouse dragging
* Dragging the mouse to the left makes the camera move to the **RIGHT** and vice versa
* Dragging the mouse to the bottom makes the camera move to the **TOP** and vice versa
(this feels a bit more natural)

**Comment by bux** [comment]
Maybe make the inverted controls the default?

**Comment by alganthe** [comment]
done
